- name: anthropic/claude-opus-4-20250514
  edit_format: diff
  cache_control: true

- name: openrouter/anthropic/claude-opus-4
  edit_format: diff
  cache_control: true

- name: openrouter/qwen/qwen3-coder
  edit_format: diff
  cache_control: true

- name: openrouter/google/gemini-2.5-flash
  edit_format: diff
  cache_control: true

- name: openrouter/google/gemini-2.5-pro
  edit_format: diff-fenced
  cache_control: true

- name: openrouter/google/gemini-3-pro-preview
  edit_format: diff-fenced
  cache_control: true